[package]
name = "events_anchor"
version = "0.1.0"
description = "Anchor reference implementation for event emission patterns"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "events_anchor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"

[dev-dependencies]
anchor-client = "0.32.1"
